### ISSUE TITLE
Coach Create Workout Adding Sets Bug

### ISSUE THREAD

**Issue by ebjorklund1** [hbrooks3/bph-front-end#27]
Description: When adding sets for a workout I have no idea how to get back to the workout plan. The only option I have is to add sets, forever and ever, only more sets.

Severity: Critical

**Comment by hbrooks3** [comment]
You use the browsers back button

**Comment by ebjorklund1** [comment]
I did figure that our after submitting this. But at least on a usability end a "submit" or "confirm" button might be nice.
